data:
  type: mock
load:
  type: constant
  stages:
  - rate: 1
    duration: 10
  num_workers: 2
api: 
  type: chat
server:
  type: vllm
  base_url: http://localhost:8000
report:
  request_lifecycle:
    summary: true
    per_stage: true
    per_request: true
tokenizer:
  pretrained_model_name_or_path: gpt2
